//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IptoFlag
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Info = new HashSet<Info>();
        }
    
        public int IdCountry { get; set; }
        public string Name { get; set; }
        public int IdContinent { get; set; }
    
        public virtual Continents Continents { get; set; }
        public virtual ICollection<Info> Info { get; set; }
    }
}
