<?xml version="1.0" encoding="utf-8"?><Database Name="GlobeDatabase" Class="GlobeDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\GlobeDatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GlobeDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Continents" Member="Continents">
    <Type Name="Continent">
      <Column Name="IdContinent" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Continent_Country" Member="Countries" ThisKey="IdContinent" OtherKey="IdContinent" Type="Country" />
    </Type>
  </Table>
  <Table Name="dbo.Countries" Member="Countries">
    <Type Name="Country">
      <Column Name="IdCountry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="IdContinent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Country_Info" Member="Infos" ThisKey="IdCountry" OtherKey="IdCountry" Type="Info" />
      <Association Name="Continent_Country" Member="Continent" ThisKey="IdContinent" OtherKey="IdContinent" Type="Continent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Info" Member="Infos">
    <Type Name="Info">
      <Column Name="IdInfo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdCountry" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InfoCountry" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IP" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Country_Info" Member="Country" ThisKey="IdCountry" OtherKey="IdCountry" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
</Database>