//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IptoFlag
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int IdInfo { get; set; }
        public int IdCountry { get; set; }
        public string InfoCountry { get; set; }
        public string IP { get; set; }
        public string Location { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Countries Countries { get; set; }
    }
}
